version: "3"

services:
  backend-service:
    image: my-kordim-backend-project-iso
    container_name: my-kordim-container
    depends_on:
      - database-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database-service:5432/endterm_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Ernar17042006
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "3333:8080"

  database-service:
    image: postgres:15
    container_name: my-kordim-db-container
    environment:
      POSTGRES_DB: endterm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ernar17042006
    ports:
      - "2345:5432"


